use std::sync::Arc;

use axum::{
    Json,
    extract::{OriginalUri, Path, State},
    http::StatusCode,
    response::{IntoResponse, Response},
};
use sea_orm::ConnectionTrait;
use serde_json::{Value, json};

use crate::{
    app::state::AppState,
    db::row_ext::QueryResultExt,
    jellyfin::{common::internal_error, providers},
    library::douban_metadata,
};

pub async fn remote_search(
    State(state): State<Arc<AppState>>,
    OriginalUri(uri): OriginalUri,
    Json(body): Json<Value>,
) -> Response {
    let item_type = remote_search_item_type(uri.path());
    let search_info = body.get("SearchInfo").unwrap_or(&body);
    let name = search_info
        .get("Name")
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty())
        .unwrap_or("Untitled")
        .trim();
    let production_year = search_info.get("Year").and_then(Value::as_i64);
    let provider_ids = search_info
        .get("ProviderIds")
        .cloned()
        .unwrap_or_else(|| json!({}));
    let provider_name = provider_ids
        .as_object()
        .and_then(|providers| providers.keys().next())
        .cloned()
        .unwrap_or_else(|| "jellyfin-rs".to_string());

    if let Some(douban_id) = provider_ids
        .as_object()
        .and_then(|providers| providers.get("Douban"))
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
    {
        let cookie = state.douban_cookie.read().await.clone();
        match douban_metadata::douban_details(
            &state.http_client,
            cookie.as_deref(),
            douban_id,
            item_type,
        )
        .await
        {
            Ok(result) => return Json(json!([result])).into_response(),
            Err(error) => tracing::warn!("Douban details failed for {douban_id}: {error:#}"),
        }
    }

    let mut combined_results = Vec::new();
    if item_type.eq_ignore_ascii_case("Movie") || item_type.eq_ignore_ascii_case("Series") {
        let cookie = state.douban_cookie.read().await.clone();
        match douban_metadata::douban_search(
            &state.http_client,
            cookie.as_deref(),
            name,
            production_year,
            item_type,
        )
        .await
        {
            Ok(results) => combined_results.extend(results),
            Err(error) => tracing::warn!("Douban search failed for {item_type}: {error:#}"),
        }
    }

    if let Some(api_key) = state
        .tmdb_api_key
        .read()
        .await
        .clone()
        .filter(|key| !key.is_empty())
    {
        let search_result = if item_type.eq_ignore_ascii_case("Movie") {
            providers::tmdb_movie_search(&state.http_client, &api_key, name, production_year).await
        } else if item_type.eq_ignore_ascii_case("Series") {
            providers::tmdb_tv_search(&state.http_client, &api_key, name, production_year).await
        } else if item_type.eq_ignore_ascii_case("Person") {
            providers::tmdb_person_search(&state.http_client, &api_key, name).await
        } else {
            Err(anyhow::anyhow!("unsupported item type"))
        };

        match search_result {
            Ok(results) => combined_results.extend(results),
            Err(error) => tracing::warn!("TMDb search failed for {item_type}: {error:#}"),
        }
    }

    if !combined_results.is_empty() {
        return Json(combined_results).into_response();
    }

    Json(json!([{
        "Name": name,
        "ProductionYear": production_year,
        "SearchProviderName": provider_name,
        "ProviderIds": provider_ids,
        "ImageUrl": null,
        "Overview": format!("Local {item_type} match generated by jellyfin-rs")
    }]))
    .into_response()
}

fn remote_search_item_type(path: &str) -> &str {
    path.trim_end_matches('/')
        .rsplit('/')
        .next()
        .unwrap_or("Item")
}

pub async fn apply_remote_search(
    State(state): State<Arc<AppState>>,
    Path(item_id): Path<String>,
    Json(body): Json<Value>,
) -> Response {
    let body = enrich_remote_search_result(&state, &item_id, body).await;
    let mut update = json!({});
    if let Some(name) = body.get("Name").cloned() {
        update["Name"] = name;
    }
    if let Some(year) = body.get("ProductionYear").cloned() {
        update["ProductionYear"] = year;
    }
    if let Some(premiere_date) = body.get("PremiereDate").cloned() {
        update["PremiereDate"] = premiere_date;
    }
    if let Some(overview) = body.get("Overview").cloned() {
        update["Overview"] = overview;
    }
    if let Some(rating) = body.get("CommunityRating").cloned() {
        update["CommunityRating"] = rating;
    }
    if let Some(runtime_ticks) = body.get("RuntimeTicks").cloned() {
        update["RuntimeTicks"] = runtime_ticks;
    }
    if let Some(provider_ids) = body.get("ProviderIds").cloned() {
        update["ProviderIds"] = provider_ids;
    }
    for key in ["Genres", "Tags", "Studios", "People"] {
        if let Some(value) = body.get(key).cloned() {
            update[key] = value;
        }
    }

    match super::item_operations::update_item_inner(&state.db, &item_id, update).await {
        Ok(true) => StatusCode::NO_CONTENT.into_response(),
        Ok(false) => (
            StatusCode::NOT_FOUND,
            Json(json!({ "Error": "Item not found" })),
        )
            .into_response(),
        Err(error) => internal_error(error),
    }
}

async fn enrich_remote_search_result(state: &AppState, item_id: &str, body: Value) -> Value {
    if let Some(douban_id) = body
        .get("ProviderIds")
        .and_then(Value::as_object)
        .and_then(|providers| providers.get("Douban"))
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
    {
        let item_type = remote_result_type_or_item_type(state, &body, item_id)
            .await
            .unwrap_or_else(|| "Movie".to_string());
        let cookie = state.douban_cookie.read().await.clone();
        match douban_metadata::douban_details(
            &state.http_client,
            cookie.as_deref(),
            douban_id,
            &item_type,
        )
        .await
        {
            Ok(details) => return merge_remote_search_values(body, details),
            Err(error) => tracing::warn!("Douban details failed: {error:#}"),
        }
    }

    let Some(api_key) = state
        .tmdb_api_key
        .read()
        .await
        .clone()
        .filter(|key| !key.is_empty())
    else {
        return body;
    };
    let Some(tmdb_id) = body
        .get("ProviderIds")
        .and_then(Value::as_object)
        .and_then(|providers| providers.get("Tmdb"))
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
    else {
        return body;
    };

    let item_type = remote_result_type_or_item_type(state, &body, item_id)
        .await
        .unwrap_or_default();

    let details = if item_type.eq_ignore_ascii_case("Series") {
        providers::tmdb_tv_details(&state.http_client, &api_key, tmdb_id).await
    } else if item_type.eq_ignore_ascii_case("Person") {
        providers::tmdb_person_details(&state.http_client, &api_key, tmdb_id).await
    } else {
        providers::tmdb_movie_details(&state.http_client, &api_key, tmdb_id).await
    };

    match details {
        Ok(details) => merge_remote_search_values(body, details),
        Err(error) => {
            tracing::warn!("TMDb details failed: {error:#}");
            body
        }
    }
}

async fn remote_result_type_or_item_type(
    state: &AppState,
    body: &Value,
    item_id: &str,
) -> Option<String> {
    if let Some(item_type) = body
        .get("Type")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
    {
        return Some(item_type.to_string());
    }
    item_type_for_id(&state.db, item_id).await.ok().flatten()
}

async fn item_type_for_id(
    db: &sea_orm::DatabaseConnection,
    item_id: &str,
) -> anyhow::Result<Option<String>> {
    let row = db
        .query_one(crate::db::helpers::pg_statement(
            "SELECT item_type FROM media_items WHERE id = ?",
            vec![item_id.into()],
        ))
        .await?;
    Ok(row.and_then(|row| row.get_str("item_type").ok()))
}

fn merge_remote_search_values(mut base: Value, details: Value) -> Value {
    for key in [
        "Name",
        "Type",
        "Overview",
        "ProductionYear",
        "PremiereDate",
        "CommunityRating",
        "RuntimeTicks",
        "EpisodeCount",
        "Countries",
        "Genres",
        "Studios",
        "People",
        "ImageUrl",
        "BackdropUrl",
    ] {
        if let Some(value) = details.get(key).filter(|value| !value.is_null()) {
            base[key] = value.clone();
        }
    }

    if let Some(details_providers) = details.get("ProviderIds").and_then(Value::as_object) {
        if !base.get("ProviderIds").is_some_and(Value::is_object) {
            base["ProviderIds"] = json!({});
        }
        for (provider, value) in details_providers {
            if value.as_str().is_some_and(|value| value.is_empty()) {
                continue;
            }
            base["ProviderIds"][provider] = value.clone();
        }
    }

    base
}

#[cfg(test)]
mod tests {
    use super::*;
    use sea_orm::ConnectionTrait;

    #[test]
    fn remote_search_item_type_uses_last_path_segment() {
        assert_eq!(
            remote_search_item_type("/Items/RemoteSearch/Movie"),
            "Movie"
        );
        assert_eq!(
            remote_search_item_type("/emby/Items/RemoteSearch/Series/"),
            "Series"
        );
    }

    #[test]
    fn merge_remote_search_values_preserves_remote_type() {
        let merged = merge_remote_search_values(
            json!({
                "Name": "Old",
                "ProviderIds": { "Tmdb": "1" }
            }),
            json!({
                "Name": "New",
                "Type": "Series",
                "ProviderIds": { "Tvdb": "2" }
            }),
        );

        assert_eq!(merged["Name"], "New");
        assert_eq!(merged["Type"], "Series");
        assert_eq!(merged["ProviderIds"]["Tmdb"], "1");
        assert_eq!(merged["ProviderIds"]["Tvdb"], "2");
    }

    #[tokio::test]
    async fn remote_result_type_falls_back_to_item_type() {
        let Some(db) = crate::db::test_db().await else {
            return;
        };
        db.execute(crate::db::helpers::pg_statement(
            "INSERT INTO media_items (id, title, path, library_id, parent_id, item_type, is_folder, modified_at, created_at, updated_at) VALUES (?, ?, ?, '', '', 'Series', 1, 1, 1, 1)",
            vec!["series1".into(), "Series".into(), "/tmp/series".into()],
        ))
        .await
        .unwrap();

        assert_eq!(
            item_type_for_id(&db, "series1").await.unwrap(),
            Some("Series".to_string())
        );
        assert_eq!(item_type_for_id(&db, "missing").await.unwrap(), None);
    }
}
