use std::sync::Arc;

use axum::{
    Json,
    extract::{OriginalUri, Path, Query, State},
    http::StatusCode,
    response::{IntoResponse, Response},
};
use sea_orm::{ColumnTrait, EntityTrait, QueryFilter};
use serde::Deserialize;
use serde_json::{Value, json};

use crate::{
    app::state::AppState,
    entities::{
        media_items::Entity as MediaItems,
        provider_ids::{self, Entity as ProviderIds},
    },
    jellyfin::{common::internal_error, providers},
    library::douban_metadata,
};

pub async fn remote_search(
    State(state): State<Arc<AppState>>,
    OriginalUri(uri): OriginalUri,
    Json(body): Json<Value>,
) -> Response {
    let item_type = remote_search_item_type(uri.path());
    let search_info = body.get("SearchInfo").unwrap_or(&body);
    let name = search_info
        .get("Name")
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty())
        .unwrap_or("Untitled")
        .trim();
    let production_year = search_info.get("Year").and_then(Value::as_i64);
    let provider_ids = search_info
        .get("ProviderIds")
        .cloned()
        .unwrap_or_else(|| json!({}));
    let provider_name = provider_ids
        .as_object()
        .and_then(|providers| providers.keys().next())
        .cloned()
        .unwrap_or_else(|| "jellyfin-rs".to_string());

    if let Some(douban_id) = provider_ids
        .as_object()
        .and_then(|providers| providers.get("Douban"))
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
    {
        let cookie = state.douban_cookie.read().await.clone();
        match douban_metadata::douban_details(
            &state.http_client,
            cookie.as_deref(),
            douban_id,
            item_type,
        )
        .await
        {
            Ok(result) => return Json(json!([result])).into_response(),
            Err(error) => tracing::warn!("Douban details failed for {douban_id}: {error:#}"),
        }
    }

    let mut combined_results = Vec::new();
    if item_type.eq_ignore_ascii_case("Movie") || item_type.eq_ignore_ascii_case("Series") {
        let cookie = state.douban_cookie.read().await.clone();
        match douban_metadata::douban_search(
            &state.http_client,
            cookie.as_deref(),
            name,
            production_year,
            item_type,
        )
        .await
        {
            Ok(results) => combined_results.extend(results),
            Err(error) => tracing::warn!("Douban search failed for {item_type}: {error:#}"),
        }
    }

    if let Some(api_key) = state
        .tmdb_api_key
        .read()
        .await
        .clone()
        .filter(|key| !key.is_empty())
    {
        let tmdb_base_url = state.tmdb_proxy_url.read().await.clone();
        let tmdb_client = state.tmdb_http_client().await;
        let search_result = if item_type.eq_ignore_ascii_case("Movie") {
            providers::tmdb_movie_search(
                &tmdb_client,
                &api_key,
                name,
                production_year,
                tmdb_base_url.as_deref(),
            )
            .await
        } else if item_type.eq_ignore_ascii_case("Series") {
            providers::tmdb_tv_search(
                &tmdb_client,
                &api_key,
                name,
                production_year,
                tmdb_base_url.as_deref(),
            )
            .await
        } else if item_type.eq_ignore_ascii_case("Person") {
            providers::tmdb_person_search(&tmdb_client, &api_key, name, tmdb_base_url.as_deref())
                .await
        } else {
            Err(anyhow::anyhow!("unsupported item type"))
        };

        match search_result {
            Ok(results) => combined_results.extend(results),
            Err(error) => tracing::warn!(
                "TMDb search failed for {item_type}: {}",
                crate::library::tmdb_metadata::redact_tmdb_error(&error)
            ),
        }
    }

    if !combined_results.is_empty() {
        return Json(combined_results).into_response();
    }

    Json(json!([{
        "Name": name,
        "ProductionYear": production_year,
        "SearchProviderName": provider_name,
        "ProviderIds": provider_ids,
        "ImageUrl": null,
        "Overview": format!("Local {item_type} match generated by jellyfin-rs")
    }]))
    .into_response()
}

fn remote_search_item_type(path: &str) -> &str {
    path.trim_end_matches('/')
        .rsplit('/')
        .next()
        .unwrap_or("Item")
}

pub async fn apply_remote_search(
    State(state): State<Arc<AppState>>,
    Path(item_id): Path<String>,
    Query(query): Query<ApplyRemoteSearchQuery>,
    Json(body): Json<Value>,
) -> Response {
    match apply_tmdb_remote_search(&state, &item_id, &body, query.replace_all_images).await {
        Ok(Some(true)) => return StatusCode::NO_CONTENT.into_response(),
        Ok(Some(false)) => {
            return (
                StatusCode::NOT_FOUND,
                Json(json!({ "Error": "Item not found" })),
            )
                .into_response();
        }
        Ok(None) => {}
        Err(error) => return internal_error(error),
    }

    let body = enrich_remote_search_result(&state, &item_id, body).await;
    let mut update = json!({});
    if let Some(name) = body.get("Name").cloned() {
        update["Name"] = name;
    }
    if let Some(year) = body.get("ProductionYear").cloned() {
        update["ProductionYear"] = year;
    }
    if let Some(premiere_date) = body.get("PremiereDate").cloned() {
        update["PremiereDate"] = premiere_date;
    }
    if let Some(overview) = body.get("Overview").cloned() {
        update["Overview"] = overview;
    }
    if let Some(rating) = body.get("CommunityRating").cloned() {
        update["CommunityRating"] = rating;
    }
    if let Some(runtime_ticks) = body.get("RuntimeTicks").cloned() {
        update["RuntimeTicks"] = runtime_ticks;
    }
    if let Some(provider_ids) = body.get("ProviderIds").cloned() {
        update["ProviderIds"] = provider_ids;
    }
    for key in ["Genres", "Tags", "Studios", "People"] {
        if let Some(value) = body.get(key).cloned() {
            update[key] = value;
        }
    }

    match super::item_operations::update_item_inner(&state.db, &item_id, update).await {
        Ok(true) => StatusCode::NO_CONTENT.into_response(),
        Ok(false) => (
            StatusCode::NOT_FOUND,
            Json(json!({ "Error": "Item not found" })),
        )
            .into_response(),
        Err(error) => internal_error(error),
    }
}

#[derive(Deserialize)]
pub struct ApplyRemoteSearchQuery {
    #[serde(
        rename = "replaceAllImages",
        alias = "ReplaceAllImages",
        default = "default_replace_all_images"
    )]
    replace_all_images: bool,
}

fn default_replace_all_images() -> bool {
    true
}

async fn apply_tmdb_remote_search(
    state: &AppState,
    item_id: &str,
    body: &Value,
    replace_all_images: bool,
) -> anyhow::Result<Option<bool>> {
    let Some(tmdb_id) = body
        .get("ProviderIds")
        .and_then(Value::as_object)
        .and_then(|providers| providers.get("Tmdb"))
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
    else {
        return Ok(None);
    };
    let Some(item) = MediaItems::find_by_id(item_id.to_string())
        .one(&state.db)
        .await?
    else {
        return Ok(Some(false));
    };
    if !matches!(item.item_type.as_str(), "Movie" | "Series") {
        return Ok(None);
    }
    let Some(api_key) = state
        .tmdb_api_key
        .read()
        .await
        .clone()
        .filter(|key| !key.is_empty())
    else {
        return Ok(None);
    };

    let normalized = super::item_operations::normalize_item_update_body(json!({
        "ProviderIds": body.get("ProviderIds").cloned().unwrap_or_else(|| json!({}))
    }))
    .map_err(|(_, message)| anyhow::anyhow!(message))?;
    let provider_ids = normalized
        .get("ProviderIds")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    ProviderIds::delete_many()
        .filter(provider_ids::Column::ItemId.eq(item_id))
        .exec(&state.db)
        .await?;
    for (provider, provider_item_id) in provider_ids {
        if let Some(provider_item_id) = provider_item_id.as_str() {
            crate::db::provider_ids::upsert(&state.db, item_id, &provider, provider_item_id)
                .await?;
        }
    }
    // Ensure the selected ID wins even if a client used non-canonical casing.
    crate::db::provider_ids::upsert(&state.db, item_id, "Tmdb", tmdb_id).await?;

    if replace_all_images {
        crate::library::tmdb_metadata::remove_tmdb_image_assets(&state.db, item_id).await?;
    }

    let tmdb_base_url = state.tmdb_proxy_url.read().await.clone();
    let tmdb_client = state.tmdb_http_client().await;
    crate::library::tmdb_metadata::fetch_and_apply_tmdb_metadata(
        &state.db,
        item_id,
        &item.item_type,
        std::path::Path::new(&item.path),
        &api_key,
        &tmdb_client,
        tmdb_base_url.as_deref(),
        crate::library::tmdb_metadata::MetadataRefreshPolicy {
            refresh_metadata: true,
            replace_metadata: true,
            refresh_images: true,
            replace_images: replace_all_images,
            force_refresh: true,
        },
    )
    .await?;
    Ok(Some(true))
}

async fn enrich_remote_search_result(state: &AppState, item_id: &str, body: Value) -> Value {
    if let Some(douban_id) = body
        .get("ProviderIds")
        .and_then(Value::as_object)
        .and_then(|providers| providers.get("Douban"))
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
    {
        let item_type = remote_result_type_or_item_type(state, &body, item_id)
            .await
            .unwrap_or_else(|| "Movie".to_string());
        let cookie = state.douban_cookie.read().await.clone();
        match douban_metadata::douban_details(
            &state.http_client,
            cookie.as_deref(),
            douban_id,
            &item_type,
        )
        .await
        {
            Ok(details) => return merge_remote_search_values(body, details),
            Err(error) => tracing::warn!("Douban details failed: {error:#}"),
        }
    }

    let Some(api_key) = state
        .tmdb_api_key
        .read()
        .await
        .clone()
        .filter(|key| !key.is_empty())
    else {
        return body;
    };
    let Some(tmdb_id) = body
        .get("ProviderIds")
        .and_then(Value::as_object)
        .and_then(|providers| providers.get("Tmdb"))
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
    else {
        return body;
    };

    let item_type = remote_result_type_or_item_type(state, &body, item_id)
        .await
        .unwrap_or_default();

    let tmdb_base_url = state.tmdb_proxy_url.read().await.clone();
    let tmdb_client = state.tmdb_http_client().await;
    let metadata_language = crate::db::settings::get_non_empty_or_default(
        &state.db,
        "PreferredMetadataLanguage",
        "zh-CN",
    )
    .await;
    let metadata_country_code =
        crate::db::settings::get_non_empty_or_default(&state.db, "MetadataCountryCode", "CN").await;
    let details = if item_type.eq_ignore_ascii_case("Series") {
        providers::tmdb_tv_details(
            &tmdb_client,
            &api_key,
            tmdb_id,
            tmdb_base_url.as_deref(),
            &metadata_language,
            &metadata_country_code,
        )
        .await
    } else if item_type.eq_ignore_ascii_case("Person") {
        providers::tmdb_person_details(&tmdb_client, &api_key, tmdb_id, tmdb_base_url.as_deref())
            .await
    } else {
        providers::tmdb_movie_details(
            &tmdb_client,
            &api_key,
            tmdb_id,
            tmdb_base_url.as_deref(),
            &metadata_language,
            &metadata_country_code,
        )
        .await
    };

    match details {
        Ok(details) => merge_remote_search_values(body, details),
        Err(error) => {
            tracing::warn!(
                "TMDb details failed: {}",
                crate::library::tmdb_metadata::redact_tmdb_error(&error)
            );
            body
        }
    }
}

async fn remote_result_type_or_item_type(
    state: &AppState,
    body: &Value,
    item_id: &str,
) -> Option<String> {
    if let Some(item_type) = body
        .get("Type")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
    {
        return Some(item_type.to_string());
    }
    item_type_for_id(&state.db, item_id).await.ok().flatten()
}

async fn item_type_for_id(
    db: &sea_orm::DatabaseConnection,
    item_id: &str,
) -> anyhow::Result<Option<String>> {
    Ok(MediaItems::find_by_id(item_id.to_string())
        .one(db)
        .await?
        .map(|item| item.item_type))
}

fn merge_remote_search_values(mut base: Value, details: Value) -> Value {
    for key in [
        "Name",
        "Type",
        "Overview",
        "ProductionYear",
        "PremiereDate",
        "CommunityRating",
        "RuntimeTicks",
        "EpisodeCount",
        "Countries",
        "Genres",
        "Studios",
        "People",
        "ImageUrl",
        "BackdropUrl",
    ] {
        if let Some(value) = details.get(key).filter(|value| !value.is_null()) {
            base[key] = value.clone();
        }
    }

    if let Some(details_providers) = details.get("ProviderIds").and_then(Value::as_object) {
        if !base.get("ProviderIds").is_some_and(Value::is_object) {
            base["ProviderIds"] = json!({});
        }
        for (provider, value) in details_providers {
            if value.as_str().is_some_and(|value| value.is_empty()) {
                continue;
            }
            base["ProviderIds"][provider] = value.clone();
        }
    }

    base
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entities::media_items;
    use sea_orm::Set;

    #[test]
    fn remote_search_item_type_uses_last_path_segment() {
        assert_eq!(
            remote_search_item_type("/Items/RemoteSearch/Movie"),
            "Movie"
        );
        assert_eq!(
            remote_search_item_type("/emby/Items/RemoteSearch/Series/"),
            "Series"
        );
    }

    #[test]
    fn merge_remote_search_values_preserves_remote_type() {
        let merged = merge_remote_search_values(
            json!({
                "Name": "Old",
                "ProviderIds": { "Tmdb": "1" }
            }),
            json!({
                "Name": "New",
                "Type": "Series",
                "ProviderIds": { "Tvdb": "2" }
            }),
        );

        assert_eq!(merged["Name"], "New");
        assert_eq!(merged["Type"], "Series");
        assert_eq!(merged["ProviderIds"]["Tmdb"], "1");
        assert_eq!(merged["ProviderIds"]["Tvdb"], "2");
    }

    #[tokio::test]
    async fn remote_result_type_falls_back_to_item_type() {
        let Some(db) = crate::db::test_db().await else {
            return;
        };
        MediaItems::insert(media_items::ActiveModel {
            id: Set("series1".to_string()),
            title: Set("Series".to_string()),
            path: Set("/tmp/series".to_string()),
            library_id: Set(String::new()),
            parent_id: Set(String::new()),
            item_type: Set("Series".to_string()),
            is_folder: Set(1),
            modified_at: Set(1),
            created_at: Set(1),
            updated_at: Set(1),
            ..Default::default()
        })
        .exec_without_returning(&db)
        .await
        .unwrap();

        assert_eq!(
            item_type_for_id(&db, "series1").await.unwrap(),
            Some("Series".to_string())
        );
        assert_eq!(item_type_for_id(&db, "missing").await.unwrap(), None);
    }
}
