use std::sync::Arc;

use axum::{
    Json,
    extract::{Path, State},
    http::StatusCode,
    response::{IntoResponse, Response},
};
use serde_json::{Value, json};

use crate::{
    app::state::AppState,
    jellyfin::{common::internal_error, providers},
};

pub async fn remote_search(
    State(state): State<Arc<AppState>>,
    Path(item_type): Path<String>,
    Json(body): Json<Value>,
) -> Response {
    let search_info = body.get("SearchInfo").unwrap_or(&body);
    let name = search_info
        .get("Name")
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty())
        .unwrap_or("Untitled")
        .trim();
    let production_year = search_info.get("Year").and_then(Value::as_i64);
    let provider_ids = search_info
        .get("ProviderIds")
        .cloned()
        .unwrap_or_else(|| json!({}));
    let provider_name = provider_ids
        .as_object()
        .and_then(|providers| providers.keys().next())
        .cloned()
        .unwrap_or_else(|| "jellyfin-rs".to_string());

    if let Some(api_key) = state.tmdb_api_key.as_deref().filter(|key| !key.is_empty()) {
        let search_result = if item_type.eq_ignore_ascii_case("Movie") {
            providers::tmdb_movie_search(&state.http_client, api_key, name, production_year).await
        } else if item_type.eq_ignore_ascii_case("Series") {
            providers::tmdb_tv_search(&state.http_client, api_key, name, production_year).await
        } else if item_type.eq_ignore_ascii_case("Person") {
            providers::tmdb_person_search(&state.http_client, api_key, name).await
        } else {
            Err(anyhow::anyhow!("unsupported item type"))
        };

        match search_result {
            Ok(results) if !results.is_empty() => return Json(results).into_response(),
            Ok(_) => {}
            Err(error) => tracing::warn!("TMDb search failed for {item_type}: {error:#}"),
        }
    }

    Json(json!([{
        "Name": name,
        "ProductionYear": production_year,
        "SearchProviderName": provider_name,
        "ProviderIds": provider_ids,
        "ImageUrl": null,
        "Overview": format!("Local {item_type} match generated by jellyfin-rs")
    }]))
    .into_response()
}

pub async fn apply_remote_search(
    State(state): State<Arc<AppState>>,
    Path(item_id): Path<String>,
    Json(body): Json<Value>,
) -> Response {
    let body = enrich_remote_search_result(&state, body).await;
    let mut update = json!({});
    if let Some(name) = body.get("Name").cloned() {
        update["Name"] = name;
    }
    if let Some(year) = body.get("ProductionYear").cloned() {
        update["ProductionYear"] = year;
    }
    if let Some(overview) = body.get("Overview").cloned() {
        update["Overview"] = overview;
    }
    if let Some(provider_ids) = body.get("ProviderIds").cloned() {
        update["ProviderIds"] = provider_ids;
    }
    for key in ["Genres", "Tags", "Studios", "People"] {
        if let Some(value) = body.get(key).cloned() {
            update[key] = value;
        }
    }

    match super::item_operations::update_item_inner(&state.db, &item_id, update).await {
        Ok(true) => StatusCode::NO_CONTENT.into_response(),
        Ok(false) => (
            StatusCode::NOT_FOUND,
            Json(json!({ "Error": "Item not found" })),
        )
            .into_response(),
        Err(error) => internal_error(error),
    }
}

async fn enrich_remote_search_result(state: &AppState, body: Value) -> Value {
    let Some(api_key) = state.tmdb_api_key.as_deref().filter(|key| !key.is_empty()) else {
        return body;
    };
    let Some(tmdb_id) = body
        .get("ProviderIds")
        .and_then(Value::as_object)
        .and_then(|providers| providers.get("Tmdb"))
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
    else {
        return body;
    };

    let item_type = body.get("Type").and_then(Value::as_str).unwrap_or("");

    let details = if item_type.eq_ignore_ascii_case("Series") {
        providers::tmdb_tv_details(&state.http_client, api_key, tmdb_id).await
    } else if item_type.eq_ignore_ascii_case("Person") {
        providers::tmdb_person_details(&state.http_client, api_key, tmdb_id).await
    } else {
        providers::tmdb_movie_details(&state.http_client, api_key, tmdb_id).await
    };

    match details {
        Ok(details) => merge_remote_search_values(body, details),
        Err(error) => {
            tracing::warn!("TMDb details failed: {error:#}");
            body
        }
    }
}

fn merge_remote_search_values(mut base: Value, details: Value) -> Value {
    for key in [
        "Name",
        "Overview",
        "ProductionYear",
        "Genres",
        "Studios",
        "People",
    ] {
        if let Some(value) = details.get(key).filter(|value| !value.is_null()) {
            base[key] = value.clone();
        }
    }

    if let Some(details_providers) = details.get("ProviderIds").and_then(Value::as_object) {
        if !base.get("ProviderIds").is_some_and(Value::is_object) {
            base["ProviderIds"] = json!({});
        }
        for (provider, value) in details_providers {
            if value.as_str().is_some_and(|value| value.is_empty()) {
                continue;
            }
            base["ProviderIds"][provider] = value.clone();
        }
    }

    base
}
