use std::path::{Path, PathBuf};

pub fn is_strm_path(path: &Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| e.eq_ignore_ascii_case("strm"))
}

pub fn read_strm_target(strm_path: &Path) -> anyhow::Result<String> {
    let content = std::fs::read_to_string(strm_path)
        .map_err(|e| anyhow::anyhow!("failed to read STRM file {}: {e}", strm_path.display()))?;
    for line in content.lines() {
        let target = line.trim().trim_start_matches('\u{feff}').trim();
        if target.is_empty() || target.starts_with('#') {
            continue;
        }
        return Ok(target.to_string());
    }
    anyhow::bail!("empty STRM file: {}", strm_path.display());
}

pub fn resolve_strm_path(strm_path: &Path) -> anyhow::Result<PathBuf> {
    let target = read_strm_target(strm_path)?;
    if is_remote_url(&target) {
        return Ok(PathBuf::from(target));
    }
    if let Some(path) = file_url_path(&target) {
        return Ok(path);
    }
    // Support relative paths (relative to the STRM file location)
    let resolved = if Path::new(&target).is_absolute() {
        PathBuf::from(target)
    } else {
        strm_path
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .join(&target)
    };
    // Normalize the path (handle .., ., etc.)
    let resolved = normalize_path(&resolved);
    Ok(resolved)
}

pub fn is_remote_url(value: &str) -> bool {
    reqwest::Url::parse(value.trim())
        .ok()
        .is_some_and(|url| matches!(url.scheme(), "http" | "https"))
}

pub fn target_extension(value: &str) -> Option<String> {
    let value = value.trim();
    let path = reqwest::Url::parse(value)
        .ok()
        .and_then(|url| {
            matches!(url.scheme(), "http" | "https" | "file").then(|| url.path().to_string())
        })
        .unwrap_or_else(|| value.split(['?', '#']).next().unwrap_or(value).to_string());
    Path::new(&path)
        .extension()
        .and_then(|extension| extension.to_str())
        .map(|extension| extension.trim().to_ascii_lowercase())
        .filter(|extension| !extension.is_empty())
}

pub fn classification_path_for_target(target: &Path, fallback: &Path) -> PathBuf {
    target_extension(&target.to_string_lossy())
        .map(|extension| fallback.with_extension(extension))
        .unwrap_or_else(|| fallback.to_path_buf())
}

/// Returns the actual media path for an item, resolving STRM files if needed.
/// Returns None if the STRM target doesn't exist or can't be read.
#[allow(dead_code)]
pub fn resolve_media_path(item_path: &Path) -> Option<PathBuf> {
    if is_strm_path(item_path) {
        resolve_strm_path(item_path).ok().filter(|p| p.exists())
    } else if item_path.exists() {
        Some(item_path.to_path_buf())
    } else {
        None
    }
}

fn normalize_path(path: &Path) -> PathBuf {
    // Simple normalization: resolve canonical if possible, otherwise return as-is
    std::fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf())
}

fn file_url_path(value: &str) -> Option<PathBuf> {
    let url = reqwest::Url::parse(value.trim()).ok()?;
    (url.scheme() == "file")
        .then(|| url.to_file_path().ok())
        .flatten()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reads_first_non_empty_non_comment_strm_line() {
        let root =
            std::env::temp_dir().join(format!("jellyfin-rs-strm-test-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&root).unwrap();
        let path = root.join("movie.strm");
        std::fs::write(
            &path,
            "\u{feff}\n# generated by test\n HTTPS://example.test/movie.mp4?token=1 \n",
        )
        .unwrap();

        assert_eq!(
            read_strm_target(&path).unwrap(),
            "HTTPS://example.test/movie.mp4?token=1"
        );
        assert!(is_remote_url(&read_strm_target(&path).unwrap()));
        assert_eq!(
            target_extension(&read_strm_target(&path).unwrap()).as_deref(),
            Some("mp4")
        );

        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn resolves_file_url_strm_target() {
        let root =
            std::env::temp_dir().join(format!("jellyfin-rs-strm-test-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&root).unwrap();
        let target = root.join("movie.mkv");
        let path = root.join("movie.strm");
        std::fs::write(&path, format!("file://{}", target.display())).unwrap();

        assert_eq!(resolve_strm_path(&path).unwrap(), target);

        let _ = std::fs::remove_dir_all(root);
    }
}
