use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "media_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub title: String,
    pub path: String,
    pub library_id: String,
    pub parent_id: String,
    pub item_type: String,
    pub extra_type: Option<String>,
    pub video_type: Option<String>,
    pub iso_type: Option<String>,
    pub video_3d_format: Option<String>,
    pub is_folder: i64,
    pub is_public: i64,
    pub container: Option<String>,
    pub overview: Option<String>,
    pub official_rating: Option<String>,
    pub custom_rating: Option<String>,
    pub extended_video_type: Option<String>,
    pub original_title: Option<String>,
    pub sort_name: Option<String>,
    pub forced_sort_name: Option<String>,
    pub lock_data: i64,
    pub locked_fields: Option<String>,
    pub tagline: Option<String>,
    pub collection_name: Option<String>,
    pub original_language: Option<String>,
    pub preferred_metadata_language: Option<String>,
    pub preferred_metadata_country_code: Option<String>,
    pub series_status: Option<String>,
    pub air_days: Option<String>,
    pub air_time: Option<String>,
    pub home_page_url: Option<String>,
    pub remote_trailers: Option<String>,
    pub production_locations: Option<String>,
    pub production_year: Option<i64>,
    pub premiere_date: Option<String>,
    pub end_date: Option<String>,
    pub runtime_ticks: Option<i64>,
    pub aspect_ratio: Option<String>,
    pub width: Option<i64>,
    pub height: Option<i64>,
    pub has_subtitles: i64,
    pub photo_metadata: Option<String>,
    pub display_order: Option<String>,
    pub size_bytes: Option<i64>,
    pub season_number: Option<i64>,
    pub episode_number: Option<i64>,
    pub episode_number_end: Option<i64>,
    pub airs_before_episode_number: Option<i64>,
    pub airs_after_season_number: Option<i64>,
    pub airs_before_season_number: Option<i64>,
    pub series_name: Option<String>,
    pub community_rating: Option<f64>,
    pub critic_rating: Option<f64>,
    pub tmdb_metadata_version: i64,
    pub modified_at: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
