mod discovery;
mod display_prefs;
mod item_detail;
mod item_operations;
mod lists;
mod metadata_mgmt;
mod recommendations;
mod remote_metadata;
mod tv_shows;

pub use crate::jellyfin::item_queries::find_media_item;
pub use discovery::{search_hints, shows_missing, shows_next_up, similar_items};
pub use display_prefs::{get_display_preferences, update_display_preferences};
pub use item_detail::{enrich_episode_list, enrich_resume_items, item_by_id, item_by_id_public};
pub use item_operations::{delete_info, delete_items, update_item};
pub use lists::{items_root, latest_items, resume_items, user_items, views};
pub(super) use lists::media_list_response;
pub use metadata_mgmt::{external_id_infos, item_counts, item_subtitles, metadata_reset, scan_handler};
pub use recommendations::{home_section_items, home_sections, movie_recommendations, user_suggestions};
pub use remote_metadata::{apply_remote_search, remote_search};
pub use tv_shows::{show_episodes, show_seasons};
